"""Add image_path to Book model

Revision ID: bf3121cf7fdf
Revises: 9ed19cde51b2
Create Date: 2025-09-30 14:45:05.687347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3121cf7fdf'
down_revision = '9ed19cde51b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
